export const projectsObject: Array<any> =[
  {
    title: 'Technology',
    index: 'technology',
    imageObject: [{
          image: 'assets/img/c1.jpg',
          thumbimage: 'assets/img/c1.jpg',
          title: 'Customer Services Application',
          description: 'roll out customer service application to help business add more revenue by providing them customer insights. Provide insightful resources to increase customer growth & product Awareness for businesses. We will show our solution will impact business growth.',
          name: 'XYZ Tech',
          'requesting': 3000,
          'price': 3000,
          'share': 20,
          'milestone': 2,
          'status': 'close',
          'endDate': '',
          'closeDays': 37

      }, {
          image: 'assets/img/c2.jpg',
          thumbimage: 'assets/img/c2.jpg',
          title: 'Decision making Application',
          description: 'Enable businesses AI Based application to increase their revenue',
          name: 'ABC Tech Inc.',
          'requesting': 3000,
          'price': 3000,
          'share': 20,
          'milestone': 2,
          'status': 'close',
          'endDate': '',
          'closeDays': 37
      }, {
          image: 'assets/img/c3.jpg',
          thumbimage: 'assets/img/c3.jpg',
          title: 'Robust Social Media Management',
          description: 'Provide insightful resources to increase customer growth & product Awareness for businesses. We will show our solution will impact business growth.Provide insightful resources to increase customer growth & product Awareness for businesses. We will show our solution will impact business growth.',
          name: 'XYZ Tech',
          'requesting': 3000,
          'price': 3000,
          'share': 20,
          'milestone': 2,
          'status': 'close',
          'endDate': '',
          'closeDays': 37
      },{
          image: 'assets/img/c4.jpg',
          thumbimage: 'assets/img/c4.jpg',
          title: 'Decision making Application',
          description: 'roll out customer service application to help business add more revenue by providing them customer insights. ..',
          name: 'XYZ Tech',
          'requesting': 3000,
          'price': 3000,
          'share': 20,
          'milestone': 2,
          'status': 'close',
          'endDate': '',
          'closeDays': 37
      }, {
          image: 'assets/img/c5.jpg',
          thumbimage: 'assets/img/c5.jpg',
          title: 'Robust Social Media Management',
          description: 'roll out customer service application to help business add more revenue by providing them customer insights. ..',
          name: 'XYZ Tech',
          'requesting': 3000,
          'price': 3000,
          'share': 20,
          'milestone': 2,
          'status': 'close',
          'endDate': '',
          'closeDays': 37
      }, {
          image: 'assets/img/c1.jpg',
          thumbimage: 'assets/img/c1.jpg',
          title: 'Example two with title.',
          description: 'roll out customer service application to help business add more revenue by providing them customer insights. ..',
          name: 'XYZ Tech',
          'requesting': 3000,
          'price': 3000,
          'share': 20,
          'milestone': 2,
          'status': 'close',
          'endDate': '',
          'closeDays': 37
      }]
  },
  {
    title: 'Retail Store',
    index: 'retail_store',
    imageObject: [{
      image: 'assets/img/c1.jpg',
      thumbimage: 'assets/img/c1.jpg',
      title: 'Customer Services Application',
      description: 'roll out customer service application to help business add more revenue by providing them customer insights. ..',
      name: 'XYZ Tech',
      'requesting': 3000,
      'price': 3000,
      'share': 20,
      'milestone': 2,
      'status': 'close',
      'endDate': '',
      'closeDays': 37
  }, {
      image: 'assets/img/c2.jpg',
      thumbimage: 'assets/img/c2.jpg',
      title: 'Decision making Application',
      description: 'Enable businesses AI Based application to increase their revenue',
      name: 'ABC Tech Inc.',
      'requesting': 3000,
      'price': 3000,
      'share': 20,
      'milestone': 2,
      'status': 'close',
      'endDate': '',
      'closeDays': 37
  }, {
      image: 'assets/img/c3.jpg',
      thumbimage: 'assets/img/c3.jpg',
      title: 'Robust Social Media Management',
      description: 'Provide insightful resources to increase customer growth & product Awareness for businesses. We will show our solution will impact business growth.',
      name: 'XYZ Tech',
      'requesting': 3000,
      'price': 3000,
      'share': 20,
      'milestone': 2,
      'status': 'close',
      'endDate': '',
      'closeDays': 37
  },{
      image: 'assets/img/c4.jpg',
      thumbimage: 'assets/img/c4.jpg',
      title: 'Decision making Application',
      description: 'roll out customer service application to help business add more revenue by providing them customer insights. ..',
      name: 'XYZ Tech',
      'requesting': 3000,
      'price': 3000,
      'share': 20,
      'milestone': 2,
      'status': 'close',
      'endDate': '',
      'closeDays': 37
  }, {
      image: 'assets/img/c5.jpg',
      thumbimage: 'assets/img/c5.jpg',
      title: 'Robust Social Media Management',
      description: 'roll out customer service application to help business add more revenue by providing them customer insights. ..',
      name: 'XYZ Tech',
      'requesting': 3000,
      'price': 3000,
      'share': 20,
      'milestone': 2,
      'status': 'close',
      'endDate': '',
      'closeDays': 37
  }, {
      image: 'assets/img/c1.jpg',
      thumbimage: 'assets/img/c1.jpg',
      title: 'Example two with title.',
      description: 'roll out customer service application to help business add more revenue by providing them customer insights. ..',
      name: 'XYZ Tech',
      'requesting': 3000,
      'price': 3000,
      'share': 20,
      'milestone': 2,
      'status': 'close',
      'endDate': '',
      'closeDays': 37
  }]
  },
  {
    title: 'Wholesale',
    index: 'wholesale',
    imageObject: [{
      image: 'assets/img/c1.jpg',
      thumbimage: 'assets/img/c1.jpg',
      title: 'Customer Services Application',
      description: 'roll out customer service application to help business add more revenue by providing them customer insights. ..',
      name: 'XYZ Tech',
      'requesting': 3000,
      'price': 3000,
      'share': 20,
      'milestone': 2,
      'status': 'close',
      'endDate': '',
      'closeDays': 37
  }, {
      image: 'assets/img/c2.jpg',
      thumbimage: 'assets/img/c2.jpg',
      title: 'Decision making Application',
      description: 'Enable businesses AI Based application to increase their revenue',
      name: 'ABC Tech Inc.',
      'requesting': 3000,
      'price': 3000,
      'share': 20,
      'milestone': 2,
      'status': 'close',
      'endDate': '',
      'closeDays': 37
  }, {
      image: 'assets/img/c3.jpg',
      thumbimage: 'assets/img/c3.jpg',
      title: 'Robust Social Media Management',
      description: 'Provide insightful resources to increase customer growth & product Awareness for businesses. We will show our solution will impact business growth.',
      name: 'XYZ Tech',
      'requesting': 3000,
      'price': 3000,
      'share': 20,
      'milestone': 2,
      'status': 'close',
      'endDate': '',
      'closeDays': 37
  },{
      image: 'assets/img/c4.jpg',
      thumbimage: 'assets/img/c4.jpg',
      title: 'Decision making Application',
      description: 'roll out customer service application to help business add more revenue by providing them customer insights. ..',
      name: 'XYZ Tech',
      'requesting': 3000,
      'price': 3000,
      'share': 20,
      'milestone': 2,
      'status': 'close',
      'endDate': '',
      'closeDays': 37
  }, {
      image: 'assets/img/c5.jpg',
      thumbimage: 'assets/img/c5.jpg',
      title: 'Robust Social Media Management',
      description: 'roll out customer service application to help business add more revenue by providing them customer insights. ..',
      name: 'XYZ Tech',
      'requesting': 3000,
      'price': 3000,
      'share': 20,
      'milestone': 2,
      'status': 'close',
      'endDate': '',
      'closeDays': 37
  }, {
      image: 'assets/img/c1.jpg',
      thumbimage: 'assets/img/c1.jpg',
      title: 'Example two with title.',
      description: 'roll out customer service application to help business add more revenue by providing them customer insights. ..',
      name: 'XYZ Tech',
      'requesting': 3000,
      'price': 3000,
      'share': 20,
      'milestone': 2,
      'status': 'close',
      'endDate': '',
      'closeDays': 37
  }]
  },
  {
    title: 'Service',
    index: 'service',
    imageObject: [{
      image: 'assets/img/c1.jpg',
      thumbimage: 'assets/img/c1.jpg',
      title: 'Customer Services Application',
      description: 'roll out customer service application to help business add more revenue by providing them customer insights. ..',
      name: 'XYZ Tech',
      'requesting': 3000,
      'price': 3000,
      'share': 20,
      'milestone': 2,
      'status': 'close',
      'endDate': '',
      'closeDays': 37
  }, {
      image: 'assets/img/c2.jpg',
      thumbimage: 'assets/img/c2.jpg',
      title: 'Decision making Application',
      description: 'Enable businesses AI Based application to increase their revenue',
      name: 'ABC Tech Inc.',
      'requesting': 3000,
      'price': 3000,
      'share': 20,
      'milestone': 2,
      'status': 'close',
      'endDate': '',
      'closeDays': 37
  }, {
      image: 'assets/img/c3.jpg',
      thumbimage: 'assets/img/c3.jpg',
      title: 'Robust Social Media Management',
      description: 'Provide insightful resources to increase customer growth & product Awareness for businesses. We will show our solution will impact business growth.',
      name: 'XYZ Tech',
      'requesting': 3000,
      'price': 3000,
      'share': 20,
      'milestone': 2,
      'status': 'close',
      'endDate': '',
      'closeDays': 37
  },{
      image: 'assets/img/c4.jpg',
      thumbimage: 'assets/img/c4.jpg',
      title: 'Decision making Application',
      description: 'roll out customer service application to help business add more revenue by providing them customer insights. ..',
      name: 'XYZ Tech',
      'requesting': 3000,
      'price': 3000,
      'share': 20,
      'milestone': 2,
      'status': 'close',
      'endDate': '',
      'closeDays': 37
  }, {
      image: 'assets/img/c5.jpg',
      thumbimage: 'assets/img/c5.jpg',
      title: 'Robust Social Media Management',
      description: 'roll out customer service application to help business add more revenue by providing them customer insights. ..',
      name: 'XYZ Tech',
      'requesting': 3000,
      'price': 3000,
      'share': 20,
      'milestone': 2,
      'status': 'close',
      'endDate': '',
      'closeDays': 37
  }, {
      image: 'assets/img/c1.jpg',
      thumbimage: 'assets/img/c1.jpg',
      title: 'Example two with title.',
      description: 'roll out customer service application to help business add more revenue by providing them customer insights. ..',
      name: 'XYZ Tech',
      'requesting': 3000,
      'price': 3000,
      'share': 20,
      'milestone': 2,
      'status': 'close',
      'endDate': '',
      'closeDays': 37
  }]
  },
  {
    title: 'Education',
    index: 'education',
    imageObject: [{
        image: 'assets/img/c1.jpg',
        thumbimage: 'assets/img/c1.jpg',
        title: 'Customer Services Application',
        description: 'roll out customer service application to help business add more revenue by providing them customer insights. ..',
        name: 'XYZ Tech',
      'requesting': 3000,
      'price': 3000,
      'share': 20,
      'milestone': 2,
      'status': 'close',
      'endDate': '',
      'closeDays': 37
    }, {
        image: 'assets/img/c2.jpg',
        thumbimage: 'assets/img/c2.jpg',
        title: 'Decision making Application',
        description: 'Enable businesses AI Based application to increase their revenue',
        name: 'ABC Tech Inc.',
      'requesting': 3000,
      'price': 3000,
      'share': 20,
      'milestone': 2,
      'status': 'close',
      'endDate': '',
      'closeDays': 37
    }, {
        image: 'assets/img/c3.jpg',
        thumbimage: 'assets/img/c3.jpg',
        title: 'Robust Social Media Management',
        description: 'Provide insightful resources to increase customer growth & product Awareness for businesses. We will show our solution will impact business growth.',
        name: 'XYZ Tech',
      'requesting': 3000,
      'price': 3000,
      'share': 20,
      'milestone': 2,
      'status': 'close',
      'endDate': '',
      'closeDays': 37
    },{
        image: 'assets/img/c4.jpg',
        thumbimage: 'assets/img/c4.jpg',
        title: 'Decision making Application',
        description: 'roll out customer service application to help business add more revenue by providing them customer insights. ..',
        name: 'XYZ Tech',
      'requesting': 3000,
      'price': 3000,
      'share': 20,
      'milestone': 2,
      'status': 'close',
      'endDate': '',
      'closeDays': 37
    }, {
        image: 'assets/img/c5.jpg',
        thumbimage: 'assets/img/c5.jpg',
        title: 'Robust Social Media Management',
        description: 'roll out customer service application to help business add more revenue by providing them customer insights. ..',
        name: 'XYZ Tech',
      'requesting': 3000,
      'price': 3000,
      'share': 20,
      'milestone': 2,
      'status': 'close',
      'endDate': '',
      'closeDays': 37
    }, {
        image: 'assets/img/c1.jpg',
        thumbimage: 'assets/img/c1.jpg',
        title: 'Example two with title.',
        description: 'roll out customer service application to help business add more revenue by providing them customer insights. ..',
        name: 'XYZ Tech',
      'requesting': 3000,
      'price': 3000,
      'share': 20,
      'milestone': 2,
      'status': 'close',
      'endDate': '',
      'closeDays': 37
    }]
  },
  {
    title: 'Transportation',
    index: 'transportation',
    imageObject: [{
        image: 'assets/img/c1.jpg',
        thumbimage: 'assets/img/c1.jpg',
        title: 'Customer Services Application',
        description: 'roll out customer service application to help business add more revenue by providing them customer insights. ..',
        name: 'XYZ Tech',
      'requesting': 3000,
      'price': 3000,
      'share': 20,
      'milestone': 2,
      'status': 'close',
      'endDate': '',
      'closeDays': 37
    }, {
        image: 'assets/img/c2.jpg',
        thumbimage: 'assets/img/c2.jpg',
        title: 'Decision making Application',
        description: 'Enable businesses AI Based application to increase their revenue',
        name: 'ABC Tech Inc.',
      'requesting': 3000,
      'price': 3000,
      'share': 20,
      'milestone': 2,
      'status': 'close',
      'endDate': '',
      'closeDays': 37
    }, {
        image: 'assets/img/c3.jpg',
        thumbimage: 'assets/img/c3.jpg',
        title: 'Robust Social Media Management',
        description: 'Provide insightful resources to increase customer growth & product Awareness for businesses. We will show our solution will impact business growth.',
        name: 'XYZ Tech',
      'requesting': 3000,
      'price': 3000,
      'share': 20,
      'milestone': 2,
      'status': 'close',
      'endDate': '',
      'closeDays': 37
    },{
        image: 'assets/img/c4.jpg',
        thumbimage: 'assets/img/c4.jpg',
        title: 'Decision making Application',
        description: 'roll out customer service application to help business add more revenue by providing them customer insights. ..',
        name: 'XYZ Tech',
      'requesting': 3000,
      'price': 3000,
      'share': 20,
      'milestone': 2,
      'status': 'close',
      'endDate': '',
      'closeDays': 37
    }, {
        image: 'assets/img/c5.jpg',
        thumbimage: 'assets/img/c5.jpg',
        title: 'Robust Social Media Management',
        description: 'roll out customer service application to help business add more revenue by providing them customer insights. ..',
        name: 'XYZ Tech',
      'requesting': 3000,
      'price': 3000,
      'share': 20,
      'milestone': 2,
      'status': 'close',
      'endDate': '',
      'closeDays': 37
    }, {
        image: 'assets/img/c1.jpg',
        thumbimage: 'assets/img/c1.jpg',
        title: 'Example two with title.',
        description: 'roll out customer service application to help business add more revenue by providing them customer insights. ..',
        name: 'XYZ Tech',
      'requesting': 3000,
      'price': 3000,
      'share': 20,
      'milestone': 2,
      'status': 'close',
      'endDate': '',
      'closeDays': 37
    }]
  },
  {
    title: 'Agriculture, Irrigation & Water',
    index: 'agriculture',
    imageObject: [{
        image: 'assets/img/c1.jpg',
        thumbimage: 'assets/img/c1.jpg',
        title: 'Customer Services Application',
        description: 'roll out customer service application to help business add more revenue by providing them customer insights. ..',
        name: 'XYZ Tech',
      'requesting': 3000,
      'price': 3000,
      'share': 20,
      'milestone': 2,
      'status': 'close',
      'endDate': '',
      'closeDays': 37
    }, {
        image: 'assets/img/c2.jpg',
        thumbimage: 'assets/img/c2.jpg',
        title: 'Decision making Application',
        description: 'Enable businesses AI Based application to increase their revenue',
        name: 'ABC Tech Inc.',
      'requesting': 3000,
      'price': 3000,
      'share': 20,
      'milestone': 2,
      'status': 'close',
      'endDate': '',
      'closeDays': 37
    }, {
        image: 'assets/img/c3.jpg',
        thumbimage: 'assets/img/c3.jpg',
        title: 'Robust Social Media Management',
        description: 'Provide insightful resources to increase customer growth & product Awareness for businesses. We will show our solution will impact business growth.',
        name: 'XYZ Tech',
      'requesting': 3000,
      'price': 3000,
      'share': 20,
      'milestone': 2,
      'status': 'close',
      'endDate': '',
      'closeDays': 37
    },{
        image: 'assets/img/c4.jpg',
        thumbimage: 'assets/img/c4.jpg',
        title: 'Decision making Application',
        description: 'roll out customer service application to help business add more revenue by providing them customer insights. ..',
        name: 'XYZ Tech',
      'requesting': 3000,
      'price': 3000,
      'share': 20,
      'milestone': 2,
      'status': 'close',
      'endDate': '',
      'closeDays': 37
    }, {
        image: 'assets/img/c5.jpg',
        thumbimage: 'assets/img/c5.jpg',
        title: 'Robust Social Media Management',
        description: 'roll out customer service application to help business add more revenue by providing them customer insights. ..',
        name: 'XYZ Tech',
      'requesting': 3000,
      'price': 3000,
      'share': 20,
      'milestone': 2,
      'status': 'close',
      'endDate': '',
      'closeDays': 37
    }, {
        image: 'assets/img/c1.jpg',
        thumbimage: 'assets/img/c1.jpg',
        title: 'Example two with title.',
        description: 'roll out customer service application to help business add more revenue by providing them customer insights. ..',
        name: 'XYZ Tech',
      'requesting': 3000,
      'price': 3000,
      'share': 20,
      'milestone': 2,
      'status': 'close',
      'endDate': '',
      'closeDays': 37
    }]
  },
  {
    title: 'Communication',
    index: 'communication',
    imageObject: [{
        image: 'assets/img/c1.jpg',
        thumbimage: 'assets/img/c1.jpg',
        title: 'Customer Services Application',
        description: 'roll out customer service application to help business add more revenue by providing them customer insights. ..',
        name: 'XYZ Tech',
      'requesting': 3000,
      'price': 3000,
      'share': 20,
      'milestone': 2,
      'status': 'close',
      'endDate': '',
      'closeDays': 37
    }, {
        image: 'assets/img/c2.jpg',
        thumbimage: 'assets/img/c2.jpg',
        title: 'Decision making Application',
        description: 'Enable businesses AI Based application to increase their revenue',
        name: 'ABC Tech Inc.',
      'requesting': 3000,
      'price': 3000,
      'share': 20,
      'milestone': 2,
      'status': 'close',
      'endDate': '',
      'closeDays': 37
    }, {
        image: 'assets/img/c3.jpg',
        thumbimage: 'assets/img/c3.jpg',
        title: 'Robust Social Media Management',
        description: 'Provide insightful resources to increase customer growth & product Awareness for businesses. We will show our solution will impact business growth.',
        name: 'XYZ Tech',
      'requesting': 3000,
      'price': 3000,
      'share': 20,
      'milestone': 2,
      'status': 'close',
      'endDate': '',
      'closeDays': 37
    },{
        image: 'assets/img/c4.jpg',
        thumbimage: 'assets/img/c4.jpg',
        title: 'Decision making Application',
        description: 'roll out customer service application to help business add more revenue by providing them customer insights. ..',
        name: 'XYZ Tech',
      'requesting': 3000,
      'price': 3000,
      'share': 20,
      'milestone': 2,
      'status': 'close',
      'endDate': '',
      'closeDays': 37
    }, {
        image: 'assets/img/c5.jpg',
        thumbimage: 'assets/img/c5.jpg',
        title: 'Robust Social Media Management',
        description: 'roll out customer service application to help business add more revenue by providing them customer insights. ..',
        name: 'XYZ Tech',
      'requesting': 3000,
      'price': 3000,
      'share': 20,
      'milestone': 2,
      'status': 'close',
      'endDate': '',
      'closeDays': 37
    }, {
        image: 'assets/img/c1.jpg',
        thumbimage: 'assets/img/c1.jpg',
        title: 'Example two with title.',
        description: 'roll out customer service application to help business add more revenue by providing them customer insights. ..',
        name: 'XYZ Tech',
      'requesting': 3000,
      'price': 3000,
      'share': 20,
      'milestone': 2,
      'status': 'close',
      'endDate': '',
      'closeDays': 37
    }]
  },
  {
    title: 'Product',
    index: 'product',
    imageObject: [{
        image: 'assets/img/c1.jpg',
        thumbimage: 'assets/img/c1.jpg',
        title: 'Customer Services Application',
        description: 'roll out customer service application to help business add more revenue by providing them customer insights. ..',
        name: 'XYZ Tech',
      'requesting': 3000,
      'price': 3000,
      'share': 20,
      'milestone': 2,
      'status': 'close',
      'endDate': '',
      'closeDays': 37
    }, {
        image: 'assets/img/c2.jpg',
        thumbimage: 'assets/img/c2.jpg',
        title: 'Decision making Application',
        description: 'Enable businesses AI Based application to increase their revenue',
        name: 'ABC Tech Inc.',
      'requesting': 3000,
      'price': 3000,
      'share': 20,
      'milestone': 2,
      'status': 'close',
      'endDate': '',
      'closeDays': 37
    }, {
        image: 'assets/img/c3.jpg',
        thumbimage: 'assets/img/c3.jpg',
        title: 'Robust Social Media Management',
        description: 'Provide insightful resources to increase customer growth & product Awareness for businesses. We will show our solution will impact business growth.Provide insightful resources to increase customer growth & product Awareness for businesses. We will show our solution will impact business growth.',
        name: 'ABC Tech Inc.',
      'requesting': 3000,
      'price': 3000,
      'share': 20,
      'milestone': 2,
      'status': 'close',
      'endDate': '',
      'closeDays': 37
    },{
        image: 'assets/img/c4.jpg',
        thumbimage: 'assets/img/c4.jpg',
        title: 'Decision making Application',
        description: 'roll out customer service application to help business add more revenue by providing them customer insights. ..',
        name: 'XYZ Tech',
      'requesting': 3000,
      'price': 3000,
      'share': 20,
      'milestone': 2,
      'status': 'close',
      'endDate': '',
      'closeDays': 37
    }, {
        image: 'assets/img/c5.jpg',
        thumbimage: 'assets/img/c5.jpg',
        title: 'Robust Social Media Management',
        description: 'roll out customer service application to help business add more revenue by providing them customer insights. ..',
        name: 'XYZ Tech',
      'requesting': 3000,
      'price': 3000,
      'share': 20,
      'milestone': 2,
      'status': 'close',
      'endDate': '',
      'closeDays': 37
    }, {
        image: 'assets/img/c1.jpg',
        thumbimage: 'assets/img/c1.jpg',
        title: 'Example two with title.',
        description: 'roll out customer service application to help business add more revenue by providing them customer insights. ..',
        name: 'XYZ Tech',
      'requesting': 3000,
      'price': 3000,
      'share': 20,
      'milestone': 2,
      'status': 'close',
      'endDate': '',
      'closeDays': 37
    }]
  },
  {
    title: 'Restaurant, Food & Beverage',
    index: 'restaurant',
    imageObject: [{
        image: 'assets/img/c1.jpg',
        thumbimage: 'assets/img/c1.jpg',
        title: 'Customer Services Application',
        description: 'roll out customer service application to help business add more revenue by providing them customer insights. ..',
        name: 'XYZ Tech',
      'requesting': 3000,
      'price': 3000,
      'share': 20,
      'milestone': 2,
      'status': 'close',
      'endDate': '',
      'closeDays': 37
    }, {
        image: 'assets/img/c2.jpg',
        thumbimage: 'assets/img/c2.jpg',
        title: 'Decision making Application',
        description: 'Enable businesses AI Based application to increase their revenue',
        name: 'ABC Tech Inc.',
      'requesting': 3000,
      'price': 3000,
      'share': 20,
      'milestone': 2,
      'status': 'close',
      'endDate': '',
      'closeDays': 37
    }, {
        image: 'assets/img/c3.jpg',
        thumbimage: 'assets/img/c3.jpg',
        title: 'Robust Social Media Management',
        description: 'Provide insightful resources to increase customer growth & product Awareness for businesses. We will show our solution will impact business growth.',
        name: 'XYZ Tech',
      'requesting': 3000,
      'price': 3000,
      'share': 20,
      'milestone': 2,
      'status': 'close',
      'endDate': '',
      'closeDays': 37
    },{
        image: 'assets/img/c4.jpg',
        thumbimage: 'assets/img/c4.jpg',
        title: 'Decision making Application',
        description: 'roll out customer service application to help business add more revenue by providing them customer insights. ..',
        name: 'XYZ Tech',
      'requesting': 3000,
      'price': 3000,
      'share': 20,
      'milestone': 2,
      'status': 'close',
      'endDate': '',
      'closeDays': 37
    }, {
        image: 'assets/img/c5.jpg',
        thumbimage: 'assets/img/c5.jpg',
        title: 'Robust Social Media Management',
        description: 'roll out customer service application to help business add more revenue by providing them customer insights. ..',
        name: 'XYZ Tech',
      'requesting': 3000,
      'price': 3000,
      'share': 20,
      'milestone': 2,
      'status': 'close',
      'endDate': '',
      'closeDays': 37
    }, {
        image: 'assets/img/c1.jpg',
        thumbimage: 'assets/img/c1.jpg',
        title: 'Example two with title.',
        description: 'roll out customer service application to help business add more revenue by providing them customer insights. ..',
        name: 'XYZ Tech',
      'requesting': 3000,
      'price': 3000,
      'share': 20,
      'milestone': 2,
      'status': 'close',
      'endDate': '',
      'closeDays': 37
    }]
  },
  {
    title: 'Tourism, Art & Culture',
    index: 'tourism',
    imageObject: [{
        image: 'assets/img/c1.jpg',
        thumbimage: 'assets/img/c1.jpg',
        title: 'Customer Services Application',
        description: 'roll out customer service application to help business add more revenue by providing them customer insights. ..',
        name: 'XYZ Tech',
      'requesting': 3000,
      'price': 3000,
      'share': 20,
      'milestone': 2,
      'status': 'close',
      'endDate': '',
      'closeDays': 37
    }, {
        image: 'assets/img/c2.jpg',
        thumbimage: 'assets/img/c2.jpg',
        title: 'Decision making Application',
        description: 'Enable businesses AI Based application to increase their revenue',
        name: 'ABC Tech Inc.',
      'requesting': 3000,
      'price': 3000,
      'share': 20,
      'milestone': 2,
      'status': 'close',
      'endDate': '',
      'closeDays': 37
    }, {
        image: 'assets/img/c3.jpg',
        thumbimage: 'assets/img/c3.jpg',
        title: 'Robust Social Media Management',
        description: 'Provide insightful resources to increase customer growth & product Awareness for businesses. We will show our solution will impact business growth.',
        name: 'XYZ Tech',
      'requesting': 3000,
      'price': 3000,
      'share': 20,
      'milestone': 2,
      'status': 'close',
      'endDate': '',
      'closeDays': 37
    },{
        image: 'assets/img/c4.jpg',
        thumbimage: 'assets/img/c4.jpg',
        title: 'Decision making Application',
        description: 'roll out customer service application to help business add more revenue by providing them customer insights. ..',
        name: 'XYZ Tech',
      'requesting': 3000,
      'price': 3000,
      'share': 20,
      'milestone': 2,
      'status': 'close',
      'endDate': '',
      'closeDays': 37
    }, {
        image: 'assets/img/c5.jpg',
        thumbimage: 'assets/img/c5.jpg',
        title: 'Robust Social Media Management',
        description: 'roll out customer service application to help business add more revenue by providing them customer insights. ..',
        name: 'XYZ Tech',
      'requesting': 3000,
      'price': 3000,
      'share': 20,
      'milestone': 2,
      'status': 'close',
      'endDate': '',
      'closeDays': 37
    }, {
        image: 'assets/img/c1.jpg',
        thumbimage: 'assets/img/c1.jpg',
        title: 'Example two with title.',
        description: 'roll out customer service application to help business add more revenue by providing them customer insights. ..',
        name: 'XYZ Tech',
      'requesting': 3000,
      'price': 3000,
      'share': 20,
      'milestone': 2,
      'status': 'close',
      'endDate': '',
      'closeDays': 37
    }]
  },
  {
    title: 'Fashion',
    index: 'fashion',
    imageObject: [{
        image: 'assets/img/c1.jpg',
        thumbimage: 'assets/img/c1.jpg',
        title: 'Customer Services Application',
        description: 'roll out customer service application to help business add more revenue by providing them customer insights. ..',
        name: 'XYZ Tech',
      'requesting': 3000,
      'price': 3000,
      'share': 20,
      'milestone': 2,
      'status': 'close',
      'endDate': '',
      'closeDays': 37
    }, {
        image: 'assets/img/c2.jpg',
        thumbimage: 'assets/img/c2.jpg',
        title: 'Decision making Application',
        description: 'Enable businesses AI Based application to increase their revenue',
        name: 'ABC Tech Inc.',
      'requesting': 3000,
      'price': 3000,
      'share': 20,
      'milestone': 2,
      'status': 'close',
      'endDate': '',
      'closeDays': 37
    }, {
        image: 'assets/img/c3.jpg',
        thumbimage: 'assets/img/c3.jpg',
        title: 'Robust Social Media Management',
        description: 'Provide insightful resources to increase customer growth & product Awareness for businesses. We will show our solution will impact business growth.',
        name: 'XYZ Tech',
      'requesting': 3000,
      'price': 3000,
      'share': 20,
      'milestone': 2,
      'status': 'close',
      'endDate': '',
      'closeDays': 37
    },{
        image: 'assets/img/c4.jpg',
        thumbimage: 'assets/img/c4.jpg',
        title: 'Decision making Application',
        description: 'roll out customer service application to help business add more revenue by providing them customer insights. ..',
        name: 'XYZ Tech',
      'requesting': 3000,
      'price': 3000,
      'share': 20,
      'milestone': 2,
      'status': 'close',
      'endDate': '',
      'closeDays': 37
    }, {
        image: 'assets/img/c5.jpg',
        thumbimage: 'assets/img/c5.jpg',
        title: 'Robust Social Media Management',
        description: 'roll out customer service application to help business add more revenue by providing them customer insights. ..',
        name: 'XYZ Tech',
      'requesting': 3000,
      'price': 3000,
      'share': 20,
      'milestone': 2,
      'status': 'close',
      'endDate': '',
      'closeDays': 37
    }, {
        image: 'assets/img/c1.jpg',
        thumbimage: 'assets/img/c1.jpg',
        title: 'Example two with title.',
        description: 'roll out customer service application to help business add more revenue by providing them customer insights. ..',
        name: 'XYZ Tech',
      'requesting': 3000,
      'price': 3000,
      'share': 20,
      'milestone': 2,
      'status': 'close',
      'endDate': '',
      'closeDays': 37
    }]
  },
  {
    title: 'Non-Profit Projects',
    index: 'non_profit_project',
    imageObject: [{
        image: 'assets/img/c1.jpg',
        thumbimage: 'assets/img/c1.jpg',
        title: 'Customer Services Application',
        description: 'roll out customer service application to help business add more revenue by providing them customer insights. ..',
        name: 'XYZ Tech',
      'requesting': 3000,
      'price': 3000,
      'share': 20,
      'milestone': 2,
      'status': 'close',
      'endDate': '',
      'closeDays': 37
    }, {
        image: 'assets/img/c2.jpg',
        thumbimage: 'assets/img/c2.jpg',
        title: 'Decision making Application',
        description: 'Enable businesses AI Based application to increase their revenue',
        name: 'ABC Tech Inc.',
      'requesting': 3000,
      'price': 3000,
      'share': 20,
      'milestone': 2,
      'status': 'close',
      'endDate': '',
      'closeDays': 37
    }, {
        image: 'assets/img/c3.jpg',
        thumbimage: 'assets/img/c3.jpg',
        title: 'Robust Social Media Management',
        description: 'Provide insightful resources to increase customer growth & product Awareness for businesses. We will show our solution will impact business growth.',
        name: 'XYZ Tech',
      'requesting': 3000,
      'price': 3000,
      'share': 20,
      'milestone': 2,
      'status': 'close',
      'endDate': '',
      'closeDays': 37
    },{
        image: 'assets/img/c4.jpg',
        thumbimage: 'assets/img/c4.jpg',
        title: 'Decision making Application',
        description: 'roll out customer service application to help business add more revenue by providing them customer insights. ..',
        name: 'XYZ Tech',
      'requesting': 3000,
      'price': 3000,
      'share': 20,
      'milestone': 2,
      'status': 'close',
      'endDate': '',
      'closeDays': 37
    }, {
        image: 'assets/img/c5.jpg',
        thumbimage: 'assets/img/c5.jpg',
        title: 'Robust Social Media Management',
        description: 'roll out customer service application to help business add more revenue by providing them customer insights. ..',
        name: 'XYZ Tech',
      'requesting': 3000,
      'price': 3000,
      'share': 20,
      'milestone': 2,
      'status': 'close',
      'endDate': '',
      'closeDays': 37
    }, {
        image: 'assets/img/c1.jpg',
        thumbimage: 'assets/img/c1.jpg',
        title: 'Example two with title.',
        description: 'roll out customer service application to help business add more revenue by providing them customer insights. ..',
        name: 'XYZ Tech',
      'requesting': 3000,
      'price': 3000,
      'share': 20,
      'milestone': 2,
      'status': 'close',
      'endDate': '',
      'closeDays': 37
    }]
  },
  {
    title: 'Funded Projects',
    index: 'funder_projects',
    imageObject: [{
        image: 'assets/img/c1.jpg',
        thumbimage: 'assets/img/c1.jpg',
        title: 'Customer Services Application',
        description: 'roll out customer service application to help business add more revenue by providing them customer insights. ..',
        name: 'XYZ Tech',
      'requesting': 3000,
      'price': 3000,
      'share': 20,
      'milestone': 2,
      'status': 'close',
      'endDate': '',
      'closeDays': 37
    }, {
        image: 'assets/img/c2.jpg',
        thumbimage: 'assets/img/c2.jpg',
        title: 'Decision making Application',
        description: 'Enable businesses AI Based application to increase their revenue',
        name: 'ABC Tech Inc.',
      'requesting': 3000,
      'price': 3000,
      'share': 20,
      'milestone': 2,
      'status': 'close',
      'endDate': '',
      'closeDays': 37
    }, {
        image: 'assets/img/c3.jpg',
        thumbimage: 'assets/img/c3.jpg',
        title: 'Robust Social Media Management',
        description: 'Provide insightful resources to increase customer growth & product Awareness for businesses. We will show our solution will impact business growth.',
        name: 'XYZ Tech',
      'requesting': 3000,
      'price': 3000,
      'share': 20,
      'milestone': 2,
      'status': 'close',
      'endDate': '',
      'closeDays': 37
    },{
        image: 'assets/img/c4.jpg',
        thumbimage: 'assets/img/c4.jpg',
        title: 'Decision making Application',
        description: 'roll out customer service application to help business add more revenue by providing them customer insights. ..',
        name: 'XYZ Tech',
      'requesting': 3000,
      'price': 3000,
      'share': 20,
      'milestone': 2,
      'status': 'close',
      'endDate': '',
      'closeDays': 37
    }, {
        image: 'assets/img/c5.jpg',
        thumbimage: 'assets/img/c5.jpg',
        title: 'Robust Social Media Management',
        description: 'roll out customer service application to help business add more revenue by providing them customer insights. ..',
        name: 'XYZ Tech',
      'requesting': 3000,
      'price': 3000,
      'share': 20,
      'milestone': 2,
      'status': 'close',
      'endDate': '',
      'closeDays': 37
    }, {
        image: 'assets/img/c1.jpg',
        thumbimage: 'assets/img/c1.jpg',
        title: 'Example two with title.',
        description: 'roll out customer service application to help business add more revenue by providing them customer insights. ..',
        name: 'XYZ Tech',
      'requesting': 3000,
      'price': 3000,
      'share': 20,
      'milestone': 2,
      'status': 'close',
      'endDate': '',
      'closeDays': 37
    }]
  },

]
